sudo: required
services:
  - docker

before_install:
  - docker build -t marathohoho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marathohoho/react-test npm test -- --coverage

after_success:
  - docker build -t marathohoho/multi-client ./client
  - docker build -t marathohoho/multi-nginx ./nginx
  - docker build -t marathohoho/multi-server ./server
  - docker build -t marathohoho/multi-worker ./worker

  # Log in into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to travis
  - docker push marathohoho/multi-client
  - docker push marathohoho/multi-nginx
  - docker push marathohoho/multi-server
  - docker push marathohoho/multi-worker
